// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zezufmhndbfyjoohgkxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplenVmbWhuZGJmeWpvb2hna3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDY3MzcsImV4cCI6MjA2NDI4MjczN30.35dQk5uyaLT-aVlooWcqW-DVv9WNTTDh9lsH7jouRuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);